//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumno
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Alumno()
        {
            this.Horarios = new HashSet<Horario>();
            this.tokenes = new HashSet<tokene>();
        }
    
        public int id_Alumnos { get; set; }
        public string nombre { get; set; }
        public string apeP { get; set; }
        public string apeM { get; set; }
        public string contrasena { get; set; }
        public string Grupos { get; set; }
        public string id_Carreras { get; set; }
        public string semestre { get; set; }
        public string OpcionCurso { get; set; }
    
        public virtual Carrera Carrera { get; set; }
        public virtual Grupos Grupos1 { get; set; }
        public virtual OpcionCurso OpcionCurso1 { get; set; }
        public virtual Semestre Semestre1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Horario> Horarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tokene> tokenes { get; set; }
    }
}
