//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Horario
    {
        public int horario1 { get; set; }
        public int id_Alumnos { get; set; }
        public string Salones { get; set; }
        public int maestroMateria { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual Maestro_Materia Maestro_Materia { get; set; }
        public virtual Salone Salone { get; set; }
    }
}
