//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tokene
    {
        public int id_token { get; set; }
        public string tokeen { get; set; }
        public Nullable<int> id_alumnosbd { get; set; }
        public Nullable<System.DateTime> tokenissued { get; set; }
        public Nullable<System.DateTime> tokendeleted { get; set; }
        public Nullable<bool> status { get; set; }
    
        public virtual Alumno Alumno { get; set; }
    }
}
